/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Global search
         * @description Search for songs, albums, artists, and playlists based on the provided query string.
         */
        get: operations["globalSearch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/songs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search for songs
         * @description Search for songs based on the provided query
         */
        get: operations["searchSongs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search for albums
         * @description Search for albums based on the provided query
         */
        get: operations["searchAlbums"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search for artists
         * @description Search for artists based on the provided query
         */
        get: operations["searchArtists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search for playlists
         * @description Search for playlists based on the provided query
         */
        get: operations["searchPlaylists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/songs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve songs by ID or link
         * @description Retrieve songs by a comma-separated list of IDs or by a direct link to the song on JioSaavn.
         */
        get: operations["getSongByIdsOrLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/songs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve song by ID
         * @description Retrieve a song by its ID. Optionally, include lyrics in the response.
         */
        get: operations["getSongById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/songs/{id}/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve song suggestions
         * @description Retrieve song suggestions based on the given song ID. This can be used to get similar songs to the one provided for infinite playback.
         */
        get: operations["getSongSuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve an album by ID or link
         * @description Retrieve an album by providing either an ID or a direct link to the album on JioSaavn.
         */
        get: operations["getAlbumByIdOrLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve artists by ID or link
         * @description Retrieve artists by ID or by a direct artist link.
         */
        get: operations["getArtistByIdOrLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve artist by ID
         * @description Retrieve artist by ID
         */
        get: operations["getArtistById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artists/{id}/songs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve artist's songs
         * @description Retrieve a list of songs for a given artist by their ID, with optional sorting and pagination.
         */
        get: operations["getArtistSongs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artists/{id}/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve artist's albums
         * @description Retrieve a list of albums for a given artist by their ID, with optional sorting and pagination.
         */
        get: operations["getArtistAlbums"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a playlist by ID or link
         * @description Retrieve a playlist by providing either an ID or a direct link to the playlist on JioSaavn.
         */
        get: operations["getPlaylistByIdOrLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    globalSearch: {
        parameters: {
            query: {
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful global search */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indicates whether the search was successful
                         * @example true
                         */
                        success: boolean;
                        /** @description Search results including songs, albums, artists, and playlists */
                        data: {
                            albums: {
                                results: {
                                    id: string;
                                    title: string;
                                    image: {
                                        quality: string;
                                        url: string;
                                    }[];
                                    artist: string;
                                    url: string;
                                    type: string;
                                    description: string;
                                    year: string;
                                    language: string;
                                    songIds: string;
                                }[];
                                position: number;
                            };
                            songs: {
                                results: {
                                    id: string;
                                    title: string;
                                    image: {
                                        quality: string;
                                        url: string;
                                    }[];
                                    album: string;
                                    url: string;
                                    type: string;
                                    description: string;
                                    primaryArtists: string;
                                    singers: string;
                                    language: string;
                                }[];
                                position: number;
                            };
                            artists: {
                                results: {
                                    id: string;
                                    title: string;
                                    image: {
                                        quality: string;
                                        url: string;
                                    }[];
                                    type: string;
                                    description: string;
                                    position: number;
                                }[];
                                position: number;
                            };
                            playlists: {
                                results: {
                                    id: string;
                                    title: string;
                                    image: {
                                        quality: string;
                                        url: string;
                                    }[];
                                    url: string;
                                    language: string;
                                    type: string;
                                    description: string;
                                }[];
                                position: number;
                            };
                            topQuery: {
                                results: {
                                    id: string;
                                    title: string;
                                    image: {
                                        quality: string;
                                        url: string;
                                    }[];
                                    album: string;
                                    url: string;
                                    type: string;
                                    description: string;
                                    primaryArtists: string;
                                    singers: string;
                                    language: string;
                                }[];
                                position: number;
                            };
                        };
                    };
                };
            };
        };
    };
    searchSongs: {
        parameters: {
            query: {
                query: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response with song search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indicates whether the song search was successful
                         * @example true
                         */
                        success: boolean;
                        /** @description Search results for songs */
                        data: {
                            total: number;
                            start: number;
                            results: {
                                id: string;
                                name: string;
                                type: string;
                                year: string | null;
                                releaseDate: string | null;
                                duration: number | null;
                                label: string | null;
                                explicitContent: boolean;
                                playCount: number | null;
                                language: string;
                                hasLyrics: boolean;
                                lyricsId: string | null;
                                url: string;
                                copyright: string | null;
                                album: {
                                    id: string | null;
                                    name: string | null;
                                    url: string | null;
                                };
                                artists: {
                                    primary: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    featured: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    all: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                };
                                image: {
                                    quality: string;
                                    url: string;
                                }[];
                                downloadUrl: {
                                    quality: string;
                                    url: string;
                                }[];
                            }[];
                        };
                    };
                };
            };
        };
    };
    searchAlbums: {
        parameters: {
            query: {
                query: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response with album search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indicates whether the album search was successful
                         * @example true
                         */
                        success: boolean;
                        /** @description Search results for albums */
                        data: {
                            total: number;
                            start: number;
                            results: {
                                id: string;
                                name: string;
                                description: string;
                                year: number | null;
                                type: string;
                                playCount: number | null;
                                language: string;
                                explicitContent: boolean;
                                artists: {
                                    primary: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    featured: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    all: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                };
                                url: string;
                                image: {
                                    quality: string;
                                    url: string;
                                }[];
                            }[];
                        };
                    };
                };
            };
        };
    };
    searchArtists: {
        parameters: {
            query: {
                query: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response with artist search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indicates whether the artist search was successful
                         * @example true
                         */
                        success: boolean;
                        /** @description Search results for artists */
                        data: {
                            total: number;
                            start: number;
                            results: {
                                id: string;
                                name: string;
                                role: string;
                                type: string;
                                image: {
                                    quality: string;
                                    url: string;
                                }[];
                                url: string;
                            }[];
                        };
                    };
                };
            };
        };
    };
    searchPlaylists: {
        parameters: {
            query: {
                query: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response with playlist search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indicates whether the playlist search was successful
                         * @example true
                         */
                        success: boolean;
                        /** @description Search results for playlist */
                        data: {
                            total: number;
                            start: number;
                            results: {
                                id: string;
                                name: string;
                                type: string;
                                image: {
                                    quality: string;
                                    url: string;
                                }[];
                                url: string;
                                songCount: number | null;
                                language: string;
                                explicitContent: boolean;
                            }[];
                        };
                    };
                };
            };
        };
    };
    getSongByIdsOrLink: {
        parameters: {
            query?: {
                ids?: string;
                link?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response with song details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indicates whether the request was successful
                         * @example true
                         */
                        success: boolean;
                        /**
                         * Song Details
                         * @description Array of song details
                         */
                        data: {
                            id: string;
                            name: string;
                            type: string;
                            year: string | null;
                            releaseDate: string | null;
                            duration: number | null;
                            label: string | null;
                            explicitContent: boolean;
                            playCount: number | null;
                            language: string;
                            hasLyrics: boolean;
                            lyricsId: string | null;
                            url: string;
                            copyright: string | null;
                            album: {
                                id: string | null;
                                name: string | null;
                                url: string | null;
                            };
                            artists: {
                                primary: {
                                    id: string;
                                    name: string;
                                    role: string;
                                    type: string;
                                    image: {
                                        quality: string;
                                        url: string;
                                    }[];
                                    url: string;
                                }[];
                                featured: {
                                    id: string;
                                    name: string;
                                    role: string;
                                    type: string;
                                    image: {
                                        quality: string;
                                        url: string;
                                    }[];
                                    url: string;
                                }[];
                                all: {
                                    id: string;
                                    name: string;
                                    role: string;
                                    type: string;
                                    image: {
                                        quality: string;
                                        url: string;
                                    }[];
                                    url: string;
                                }[];
                            };
                            image: {
                                quality: string;
                                url: string;
                            }[];
                            downloadUrl: {
                                quality: string;
                                url: string;
                            }[];
                        }[];
                    };
                };
            };
            /** @description Bad request when query parameters are missing or invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Song not found with the given ID or link */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSongById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response with song details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indicates whether the request was successful
                         * @example true
                         */
                        success: boolean;
                        /** @description Array of songs */
                        data: {
                            id: string;
                            name: string;
                            type: string;
                            year: string | null;
                            releaseDate: string | null;
                            duration: number | null;
                            label: string | null;
                            explicitContent: boolean;
                            playCount: number | null;
                            language: string;
                            hasLyrics: boolean;
                            lyricsId: string | null;
                            url: string;
                            copyright: string | null;
                            album: {
                                id: string | null;
                                name: string | null;
                                url: string | null;
                            };
                            artists: {
                                primary: {
                                    id: string;
                                    name: string;
                                    role: string;
                                    type: string;
                                    image: {
                                        quality: string;
                                        url: string;
                                    }[];
                                    url: string;
                                }[];
                                featured: {
                                    id: string;
                                    name: string;
                                    role: string;
                                    type: string;
                                    image: {
                                        quality: string;
                                        url: string;
                                    }[];
                                    url: string;
                                }[];
                                all: {
                                    id: string;
                                    name: string;
                                    role: string;
                                    type: string;
                                    image: {
                                        quality: string;
                                        url: string;
                                    }[];
                                    url: string;
                                }[];
                            };
                            image: {
                                quality: string;
                                url: string;
                            }[];
                            downloadUrl: {
                                quality: string;
                                url: string;
                            }[];
                        }[];
                    };
                };
            };
            /** @description Bad request when query parameters are missing or invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Song not found for the given ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSongSuggestions: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response with song suggestions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indicates whether the request was successful
                         * @example true
                         */
                        success: boolean;
                        /** @description Array of song suggestions */
                        data: {
                            id: string;
                            name: string;
                            type: string;
                            year: string | null;
                            releaseDate: string | null;
                            duration: number | null;
                            label: string | null;
                            explicitContent: boolean;
                            playCount: number | null;
                            language: string;
                            hasLyrics: boolean;
                            lyricsId: string | null;
                            url: string;
                            copyright: string | null;
                            album: {
                                id: string | null;
                                name: string | null;
                                url: string | null;
                            };
                            artists: {
                                primary: {
                                    id: string;
                                    name: string;
                                    role: string;
                                    type: string;
                                    image: {
                                        quality: string;
                                        url: string;
                                    }[];
                                    url: string;
                                }[];
                                featured: {
                                    id: string;
                                    name: string;
                                    role: string;
                                    type: string;
                                    image: {
                                        quality: string;
                                        url: string;
                                    }[];
                                    url: string;
                                }[];
                                all: {
                                    id: string;
                                    name: string;
                                    role: string;
                                    type: string;
                                    image: {
                                        quality: string;
                                        url: string;
                                    }[];
                                    url: string;
                                }[];
                            };
                            image: {
                                quality: string;
                                url: string;
                            }[];
                            downloadUrl: {
                                quality: string;
                                url: string;
                            }[];
                        }[];
                    };
                };
            };
        };
    };
    getAlbumByIdOrLink: {
        parameters: {
            query?: {
                id?: string;
                link?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response with album details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indicates the success status of the request.
                         * @example true
                         */
                        success: boolean;
                        /**
                         * Album Details
                         * @description The detailed information of the album.
                         */
                        data: {
                            id: string;
                            name: string;
                            description: string;
                            year: number | null;
                            type: string;
                            playCount: number | null;
                            language: string;
                            explicitContent: boolean;
                            artists: {
                                primary: {
                                    id: string;
                                    name: string;
                                    role: string;
                                    type: string;
                                    image: {
                                        quality: string;
                                        url: string;
                                    }[];
                                    url: string;
                                }[];
                                featured: {
                                    id: string;
                                    name: string;
                                    role: string;
                                    type: string;
                                    image: {
                                        quality: string;
                                        url: string;
                                    }[];
                                    url: string;
                                }[];
                                all: {
                                    id: string;
                                    name: string;
                                    role: string;
                                    type: string;
                                    image: {
                                        quality: string;
                                        url: string;
                                    }[];
                                    url: string;
                                }[];
                            };
                            songCount: number | null;
                            url: string;
                            image: {
                                quality: string;
                                url: string;
                            }[];
                            songs: {
                                id: string;
                                name: string;
                                type: string;
                                year: string | null;
                                releaseDate: string | null;
                                duration: number | null;
                                label: string | null;
                                explicitContent: boolean;
                                playCount: number | null;
                                language: string;
                                hasLyrics: boolean;
                                lyricsId: string | null;
                                url: string;
                                copyright: string | null;
                                album: {
                                    id: string | null;
                                    name: string | null;
                                    url: string | null;
                                };
                                artists: {
                                    primary: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    featured: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    all: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                };
                                image: {
                                    quality: string;
                                    url: string;
                                }[];
                                downloadUrl: {
                                    quality: string;
                                    url: string;
                                }[];
                            }[] | null;
                        };
                    };
                };
            };
            /** @description Bad request due to missing or invalid query parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The album could not be found with the provided ID or link. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getArtistByIdOrLink: {
        parameters: {
            query?: {
                id?: string;
                link?: string;
                page?: number;
                songCount?: number;
                albumCount?: number;
                sortBy?: string;
                sortOrder?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response with artist details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indicates whether the request was successful
                         * @example true
                         */
                        success: boolean;
                        /** @description Artist details */
                        data: {
                            id: string;
                            name: string;
                            url: string;
                            type: string;
                            image: {
                                quality: string;
                                url: string;
                            }[];
                            followerCount: number | null;
                            fanCount: string | null;
                            isVerified: boolean | null;
                            dominantLanguage: string | null;
                            dominantType: string | null;
                            bio: {
                                text: string | null;
                                title: string | null;
                                sequence: number | null;
                            }[] | null;
                            dob: string | null;
                            fb: string | null;
                            twitter: string | null;
                            wiki: string | null;
                            availableLanguages: string[];
                            isRadioPresent: boolean | null;
                            topSongs: {
                                id: string;
                                name: string;
                                type: string;
                                year: string | null;
                                releaseDate: string | null;
                                duration: number | null;
                                label: string | null;
                                explicitContent: boolean;
                                playCount: number | null;
                                language: string;
                                hasLyrics: boolean;
                                lyricsId: string | null;
                                url: string;
                                copyright: string | null;
                                album: {
                                    id: string | null;
                                    name: string | null;
                                    url: string | null;
                                };
                                artists: {
                                    primary: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    featured: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    all: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                };
                                image: {
                                    quality: string;
                                    url: string;
                                }[];
                                downloadUrl: {
                                    quality: string;
                                    url: string;
                                }[];
                            }[] | null;
                            topAlbums: {
                                id: string;
                                name: string;
                                description: string;
                                year: number | null;
                                type: string;
                                playCount: number | null;
                                language: string;
                                explicitContent: boolean;
                                artists: {
                                    primary: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    featured: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    all: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                };
                                songCount: number | null;
                                url: string;
                                image: {
                                    quality: string;
                                    url: string;
                                }[];
                                songs: {
                                    id: string;
                                    name: string;
                                    type: string;
                                    year: string | null;
                                    releaseDate: string | null;
                                    duration: number | null;
                                    label: string | null;
                                    explicitContent: boolean;
                                    playCount: number | null;
                                    language: string;
                                    hasLyrics: boolean;
                                    lyricsId: string | null;
                                    url: string;
                                    copyright: string | null;
                                    album: {
                                        id: string | null;
                                        name: string | null;
                                        url: string | null;
                                    };
                                    artists: {
                                        primary: {
                                            id: string;
                                            name: string;
                                            role: string;
                                            type: string;
                                            image: {
                                                quality: string;
                                                url: string;
                                            }[];
                                            url: string;
                                        }[];
                                        featured: {
                                            id: string;
                                            name: string;
                                            role: string;
                                            type: string;
                                            image: {
                                                quality: string;
                                                url: string;
                                            }[];
                                            url: string;
                                        }[];
                                        all: {
                                            id: string;
                                            name: string;
                                            role: string;
                                            type: string;
                                            image: {
                                                quality: string;
                                                url: string;
                                            }[];
                                            url: string;
                                        }[];
                                    };
                                    image: {
                                        quality: string;
                                        url: string;
                                    }[];
                                    downloadUrl: {
                                        quality: string;
                                        url: string;
                                    }[];
                                }[] | null;
                            }[] | null;
                            singles: {
                                id: string;
                                name: string;
                                type: string;
                                year: string | null;
                                releaseDate: string | null;
                                duration: number | null;
                                label: string | null;
                                explicitContent: boolean;
                                playCount: number | null;
                                language: string;
                                hasLyrics: boolean;
                                lyricsId: string | null;
                                url: string;
                                copyright: string | null;
                                album: {
                                    id: string | null;
                                    name: string | null;
                                    url: string | null;
                                };
                                artists: {
                                    primary: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    featured: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    all: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                };
                                image: {
                                    quality: string;
                                    url: string;
                                }[];
                                downloadUrl: {
                                    quality: string;
                                    url: string;
                                }[];
                            }[] | null;
                            similarArtists: {
                                id: string;
                                name: string;
                                url: string;
                                image: {
                                    quality: string;
                                    url: string;
                                }[];
                                languages: {
                                    [key: string]: string;
                                } | null;
                                wiki: string;
                                dob: string;
                                fb: string;
                                twitter: string;
                                isRadioPresent: boolean;
                                type: string;
                                dominantType: string;
                                aka: string;
                                bio: string | null;
                                similarArtists: {
                                    id: string;
                                    name: string;
                                }[] | null;
                            }[] | null;
                        };
                    };
                };
            };
        };
    };
    getArtistById: {
        parameters: {
            query?: {
                page?: number;
                songCount?: number;
                albumCount?: number;
                sortBy?: "popularity" | "latest" | "alphabetical";
                sortOrder?: "asc" | "desc";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response with artist details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indicates whether the request was successful
                         * @example true
                         */
                        success: boolean;
                        data: {
                            id: string;
                            name: string;
                            url: string;
                            type: string;
                            image: {
                                quality: string;
                                url: string;
                            }[];
                            followerCount: number | null;
                            fanCount: string | null;
                            isVerified: boolean | null;
                            dominantLanguage: string | null;
                            dominantType: string | null;
                            bio: {
                                text: string | null;
                                title: string | null;
                                sequence: number | null;
                            }[] | null;
                            dob: string | null;
                            fb: string | null;
                            twitter: string | null;
                            wiki: string | null;
                            availableLanguages: string[];
                            isRadioPresent: boolean | null;
                            topSongs: {
                                id: string;
                                name: string;
                                type: string;
                                year: string | null;
                                releaseDate: string | null;
                                duration: number | null;
                                label: string | null;
                                explicitContent: boolean;
                                playCount: number | null;
                                language: string;
                                hasLyrics: boolean;
                                lyricsId: string | null;
                                url: string;
                                copyright: string | null;
                                album: {
                                    id: string | null;
                                    name: string | null;
                                    url: string | null;
                                };
                                artists: {
                                    primary: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    featured: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    all: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                };
                                image: {
                                    quality: string;
                                    url: string;
                                }[];
                                downloadUrl: {
                                    quality: string;
                                    url: string;
                                }[];
                            }[] | null;
                            topAlbums: {
                                id: string;
                                name: string;
                                description: string;
                                year: number | null;
                                type: string;
                                playCount: number | null;
                                language: string;
                                explicitContent: boolean;
                                artists: {
                                    primary: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    featured: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    all: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                };
                                songCount: number | null;
                                url: string;
                                image: {
                                    quality: string;
                                    url: string;
                                }[];
                                songs: {
                                    id: string;
                                    name: string;
                                    type: string;
                                    year: string | null;
                                    releaseDate: string | null;
                                    duration: number | null;
                                    label: string | null;
                                    explicitContent: boolean;
                                    playCount: number | null;
                                    language: string;
                                    hasLyrics: boolean;
                                    lyricsId: string | null;
                                    url: string;
                                    copyright: string | null;
                                    album: {
                                        id: string | null;
                                        name: string | null;
                                        url: string | null;
                                    };
                                    artists: {
                                        primary: {
                                            id: string;
                                            name: string;
                                            role: string;
                                            type: string;
                                            image: {
                                                quality: string;
                                                url: string;
                                            }[];
                                            url: string;
                                        }[];
                                        featured: {
                                            id: string;
                                            name: string;
                                            role: string;
                                            type: string;
                                            image: {
                                                quality: string;
                                                url: string;
                                            }[];
                                            url: string;
                                        }[];
                                        all: {
                                            id: string;
                                            name: string;
                                            role: string;
                                            type: string;
                                            image: {
                                                quality: string;
                                                url: string;
                                            }[];
                                            url: string;
                                        }[];
                                    };
                                    image: {
                                        quality: string;
                                        url: string;
                                    }[];
                                    downloadUrl: {
                                        quality: string;
                                        url: string;
                                    }[];
                                }[] | null;
                            }[] | null;
                            singles: {
                                id: string;
                                name: string;
                                type: string;
                                year: string | null;
                                releaseDate: string | null;
                                duration: number | null;
                                label: string | null;
                                explicitContent: boolean;
                                playCount: number | null;
                                language: string;
                                hasLyrics: boolean;
                                lyricsId: string | null;
                                url: string;
                                copyright: string | null;
                                album: {
                                    id: string | null;
                                    name: string | null;
                                    url: string | null;
                                };
                                artists: {
                                    primary: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    featured: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    all: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                };
                                image: {
                                    quality: string;
                                    url: string;
                                }[];
                                downloadUrl: {
                                    quality: string;
                                    url: string;
                                }[];
                            }[] | null;
                            similarArtists: {
                                id: string;
                                name: string;
                                url: string;
                                image: {
                                    quality: string;
                                    url: string;
                                }[];
                                languages: {
                                    [key: string]: string;
                                } | null;
                                wiki: string;
                                dob: string;
                                fb: string;
                                twitter: string;
                                isRadioPresent: boolean;
                                type: string;
                                dominantType: string;
                                aka: string;
                                bio: string | null;
                                similarArtists: {
                                    id: string;
                                    name: string;
                                }[] | null;
                            }[] | null;
                        };
                    };
                };
            };
            /** @description Artist not found for the given ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getArtistSongs: {
        parameters: {
            query?: {
                page?: number;
                sortBy?: "popularity" | "latest" | "alphabetical";
                sortOrder?: "asc" | "desc";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response with a list of songs for the artist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indicates whether the request was successful
                         * @example true
                         */
                        success: boolean;
                        /** @description An array of songs associated with the artist */
                        data: {
                            total: number;
                            songs: {
                                id: string;
                                name: string;
                                type: string;
                                year: string | null;
                                releaseDate: string | null;
                                duration: number | null;
                                label: string | null;
                                explicitContent: boolean;
                                playCount: number | null;
                                language: string;
                                hasLyrics: boolean;
                                lyricsId: string | null;
                                url: string;
                                copyright: string | null;
                                album: {
                                    id: string | null;
                                    name: string | null;
                                    url: string | null;
                                };
                                artists: {
                                    primary: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    featured: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    all: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                };
                                image: {
                                    quality: string;
                                    url: string;
                                }[];
                                downloadUrl: {
                                    quality: string;
                                    url: string;
                                }[];
                            }[];
                        };
                    };
                };
            };
            /** @description Artist not found for the given ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getArtistAlbums: {
        parameters: {
            query?: {
                page?: number;
                sortBy?: "popularity" | "latest" | "alphabetical";
                sortOrder?: "asc" | "desc";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response with a list of albums for the artist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indicates whether the request was successful
                         * @example true
                         */
                        success: boolean;
                        /** @description An array of albums associated with the artist */
                        data: {
                            total: number;
                            albums: {
                                id: string;
                                name: string;
                                description: string;
                                year: number | null;
                                type: string;
                                playCount: number | null;
                                language: string;
                                explicitContent: boolean;
                                artists: {
                                    primary: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    featured: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    all: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                };
                                songCount: number | null;
                                url: string;
                                image: {
                                    quality: string;
                                    url: string;
                                }[];
                                songs: {
                                    id: string;
                                    name: string;
                                    type: string;
                                    year: string | null;
                                    releaseDate: string | null;
                                    duration: number | null;
                                    label: string | null;
                                    explicitContent: boolean;
                                    playCount: number | null;
                                    language: string;
                                    hasLyrics: boolean;
                                    lyricsId: string | null;
                                    url: string;
                                    copyright: string | null;
                                    album: {
                                        id: string | null;
                                        name: string | null;
                                        url: string | null;
                                    };
                                    artists: {
                                        primary: {
                                            id: string;
                                            name: string;
                                            role: string;
                                            type: string;
                                            image: {
                                                quality: string;
                                                url: string;
                                            }[];
                                            url: string;
                                        }[];
                                        featured: {
                                            id: string;
                                            name: string;
                                            role: string;
                                            type: string;
                                            image: {
                                                quality: string;
                                                url: string;
                                            }[];
                                            url: string;
                                        }[];
                                        all: {
                                            id: string;
                                            name: string;
                                            role: string;
                                            type: string;
                                            image: {
                                                quality: string;
                                                url: string;
                                            }[];
                                            url: string;
                                        }[];
                                    };
                                    image: {
                                        quality: string;
                                        url: string;
                                    }[];
                                    downloadUrl: {
                                        quality: string;
                                        url: string;
                                    }[];
                                }[] | null;
                            }[];
                        };
                    };
                };
            };
            /** @description Artist not found for the given ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPlaylistByIdOrLink: {
        parameters: {
            query?: {
                id?: string;
                link?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response with playlist details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indicates the success status of the request.
                         * @example true
                         */
                        success: boolean;
                        /**
                         * Playlist Details
                         * @description The detailed information of the playlist.
                         */
                        data: {
                            id: string;
                            name: string;
                            description: string | null;
                            year: number | null;
                            type: string;
                            playCount: number | null;
                            language: string;
                            explicitContent: boolean;
                            songCount: number | null;
                            url: string;
                            image: {
                                quality: string;
                                url: string;
                            }[];
                            songs: {
                                id: string;
                                name: string;
                                type: string;
                                year: string | null;
                                releaseDate: string | null;
                                duration: number | null;
                                label: string | null;
                                explicitContent: boolean;
                                playCount: number | null;
                                language: string;
                                hasLyrics: boolean;
                                lyricsId: string | null;
                                url: string;
                                copyright: string | null;
                                album: {
                                    id: string | null;
                                    name: string | null;
                                    url: string | null;
                                };
                                artists: {
                                    primary: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    featured: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                    all: {
                                        id: string;
                                        name: string;
                                        role: string;
                                        type: string;
                                        image: {
                                            quality: string;
                                            url: string;
                                        }[];
                                        url: string;
                                    }[];
                                };
                                image: {
                                    quality: string;
                                    url: string;
                                }[];
                                downloadUrl: {
                                    quality: string;
                                    url: string;
                                }[];
                            }[] | null;
                            artists: {
                                id: string;
                                name: string;
                                role: string;
                                type: string;
                                image: {
                                    quality: string;
                                    url: string;
                                }[];
                                url: string;
                            }[] | null;
                        };
                    };
                };
            };
            /** @description Bad request due to missing or invalid query parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The playlist could not be found with the provided ID or link. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
