import { HomeSection, Playlist, QuickPick, SpeedDialItem } from "./types";

// Dummy data removed — Quick Picks are now sourced from the live JioSaavn API.
export const quickPickColumns: QuickPick[][] = [];

export const speedDialItems: SpeedDialItem[] = [];

export const playlists: Playlist[] = [];

export const homeSections: HomeSection[] = [
  { id: "quick-picks", type: "quickPicks" },
  { id: "speed-dial", type: "speedDial" },
  { id: "trending", type: "trending" },
];

// dont wipe out this 

// {"id":"n1u90OMO","title":"CHANEL","subtitle":"Tyla - CHANEL","header_desc":"","type":"song","perma_url":"https://www.jiosaavn.com/song/chanel/HlkeCER-enw","image":"https://c.saavncdn.com/416/CHANEL-English-2025-20260414215525-500x500.jpg?bch=493444","language":"english","year":"2025","play_count":"1096001","explicit_content":"1","list_count":"0","list_type":"","list":"","more_info":{"music":"Bibi Bourelly, Richard Olowaranta Mbu Isong, Ian Kirkpatrick, Douglas Ford, Tyla Seethal","album_id":"69065993","album":"CHANEL","label":"Epic","label_id":"35297","origin":"none","is_dolby_content":false,"320kbps":"true","encrypted_media_url":"ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyPJKGZQDW1ELtzHbWY7cqsRB99gRD2UpPMlN0iCrr3rFoDRJXFakCAxw7tS9a8Gtq","encrypted_cache_url":"","encrypted_drm_cache_url":"","encrypted_drm_media_url":"ID2ieOjCrwdjlkMElYlzWCptgNdUpWD8CdxSudnbGugTGleDBQOSPwjFuVc4RNzP63ZuXAmCmJj+Lgp4QpGjj492mytrdt3FSpts30PcFYg=","album_url":"https://www.jiosaavn.com/album/chanel/l25yI1m-vWw_","duration":"188","rights":{"code":"0","cacheable":"true"},"cache_state":"false","has_lyrics":"false","lyrics_snippet":"","starred":"false","copyright_text":"(P) 2025 FAX Records, under exclusive license to Epic Records, a division of Sony Music Entertainment","artistMap":{"primary_artists":[{"id":"1322607","name":"Tyla","role":"","image":"https://c.saavncdn.com/artists/Tyla_001_20250122115738_150x150.jpg","type":"artist","perma_url":"https://www.jiosaavn.com/artist/tyla-songs/AlMmD4N8pxg_"}],"featured_artists":[],"artists":[{"id":"834044","name":"Bibi Bourelly","role":"","image":"https://c.saavncdn.com/385/Ballin-English-2016-150x150.jpg","type":"artist","perma_url":"https://www.jiosaavn.com/artist/bibi-bourelly-songs/ioBhoiPIUaY_"},{"id":"23712562","name":"Richard Olowaranta Mbu Isong","role":"","image":"","type":"artist","perma_url":"https://www.jiosaavn.com/artist/richard-olowaranta-mbu-isong-songs/gso2TRYaueE_"},{"id":"577489","name":"Ian Kirkpatrick","role":"","image":"","type":"artist","perma_url":"https://www.jiosaavn.com/artist/ian-kirkpatrick-songs/zsvJSi5q-As_"},{"id":"2907560","name":"Douglas Ford","role":"","image":"","type":"artist","perma_url":"https://www.jiosaavn.com/artist/douglas-ford-songs/reKMIwsytz8_"},{"id":"9774742","name":"Tyla Seethal","role":"","image":"","type":"artist","perma_url":"https://www.jiosaavn.com/artist/tyla-seethal-songs/ROuigVbnOAM_"},{"id":"1322607","name":"Tyla","role":"","image":"https://c.saavncdn.com/artists/Tyla_001_20250122115738_150x150.jpg","type":"artist","perma_url":"https://www.jiosaavn.com/artist/tyla-songs/AlMmD4N8pxg_"}]},"release_date":"2025-10-24","label_url":"/label/epic-albums/NWuLW6qSMuU_","vcode":"010912023419144","vlink":"https://jiotunepreview.jio.com/content/Converted/010912023376150.mp3","triller_available":false,"request_jiotune_flag":false,"webp":"true"},"modules":null,"button_tooltip_info":[],"pro_hva_campaigns":[]},